INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (3, 'กลุ่มงานเทคโนโลยีสารสนเทศ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (4, 'ห้องเทรนนิ่ง');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (5, 'คลินิคอายุรกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (6, 'ห้องตรวจคลื่นไฟฟ้าหัวใจ (EKG)');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (7, 'คลินิคศัลยกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (8, 'คลินิคศัลยกรรมกระดูก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (9, 'คลินิคโรคทั่วไป (GP)');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (10, 'ห้องฉีดยา');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (11, 'เวชระเบียนผู้ป่วยนอก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (12, 'เวชระเบียนผู้ป่วยใน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (13, 'ห้องตรวจเด็ก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (14, 'ห้องตรวจนรีเวช');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (15, 'คลินิคฝากครรภ์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (16, 'งานวางแผนครอบครัว');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (17, 'คลินิก ARI เด็ก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (18, 'คลินิก ARI ผู้ใหญ่');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (19, 'คลินิกเบาหวาน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (20, 'ห้องตรวจนภาคลีนิก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (21, 'ศูนย์สุขภาพชุมชนแม่สอด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (22, 'ห้องตรวจตา');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (23, 'ห้องตรวจ หู คอ จมูก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (24, 'ห้องตรวจการได้ยิน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (25, 'คลินิควัณโรค');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (27, 'EMS');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (28, 'งานกายภาพบำบัด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (29, 'กิจกรรมบำบัด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (30, 'งานไตเทียม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (31, 'งานแผนไทย');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (32, 'คลินิคกามโรค');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (33, 'งานห้องผ่าตัด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (34, 'งานวิสัญญีพยาบาล');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (35, 'กลุ่มงานทันตกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (36, 'ห้องจ่ายยานอกผู้ป่วยนอก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (37, 'ห้องจ่ายยาผู้ป่วยใน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (38, 'ห้องจ่ายยา PCC');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (39, 'ห้องตรวจ GASTROSCOPE');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (40, 'งานรังสีวินิจฉัย');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (41, 'ห้องตรวจ MRI');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (42, 'กลุ่มงานจิตเวช');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (43, 'งานขาเทียม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (44, 'งานห้องคลอด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (45, 'งานธนาคารเลือด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (46, 'หอผู้ป่วยกุมารเวชกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (47, 'หอผู้ป่วยทารกแรกเกิด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (48, 'หอผู้ป่วยอายุรกรรมชาย 1');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (49, 'หอผู้ป่วยอายุรกรรมชาย 2');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (50, 'หอผู้ป่วยศัลยกรรมหญิง 1');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (51, 'หอผู้ป่วยอายุรกรรมหญิง 1');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (52, 'หอผู้ป่วยศัลยกรรมชาย 1');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (53, 'หอผู้ป่วยศัลยกรรมชาย 2');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (54, 'หอผู้ป่วยอายุรกรรมหญิง 2');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (55, 'หอผู้ป่วยพิเศษ 1 ชั้น 5');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (56, 'หอผู้ป่วยพิเศษ 1 ชั้น 6');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (57, 'หอผู้ป่วยพิเศษ 2 ชั้น 6');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (58, 'หอผู้ป่วยพิเศษ 2 ชั้น 7');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (59, 'หอผู้ป่วยพิเศษ 3 ชั้น 4');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (60, 'หอผู้ป่วยพิเศษ 3 ชั้น 5');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (61, 'หอผู้ป่วยพิเศษ 3 ชั้น 6');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (62, 'ห้องผู้ป่วยหนัก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (63, 'ห้องผู้ป่วยหนักเด็ก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (64, 'ห้องผู้ป่วยหนักศัลยกรรมประสาท');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (65, 'หอผู้ป่วยนรีเวชกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (66, 'หอผู้ป่วยสูติกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (67, 'หอผู้ป่วยจิตเวช');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (68, 'งานห้องสมุด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (69, 'งานเวชนิทัศน์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (70, 'งานธุรการ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (71, 'งานทรัพยากรบุคคล');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (72, 'งานเลขานุการ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (73, 'งานการเงิน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (74, 'งานบัญชี');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (75, 'งานพัสดุ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (76, 'ห้องรองผู้อำนวยการ ฝ่ายการแพทย์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (77, 'ห้องรองผู้อำนวยการ ฝ่ายบริหาร');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (78, 'ห้อง ผู้อำนวยการ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (79, 'บ้านพักผู้อำนวยการ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (80, 'สำนักงานฝ่ายการพยาบาล');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (81, 'งานวิจัยและพัฒนาการพยาบาล');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (82, 'ฝ่ายเวชกรรมสังคม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (83, 'งานอาชีวเวชกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (84, 'ฝ่ายสุขศึกษา');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (85, 'งานป้องกันและควบคุมการติดเชื้อIC');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (86, 'ห้องพักแพทย์ (ชั้น7)');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (87, 'ห้องพักแพทย์ (ER)');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (88, 'กลุ่มงานพยาธิวิทยากายวิภาค');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (89, 'งานยานพาหนะ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (90, 'ห้องการเงิน ห้องจ่ายยา');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (91, 'ฝ่ายโภชนาการ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (92, 'งานจ่ายกลาง');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (93, 'งานซักฟอก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (94, 'ประชาสัมพันธ์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (95, 'คลังพัสดุ (หลัง)');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (96, 'งานช่าง และซ่อมบำรุง');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (97, 'งานคลังเวชภัณฑ์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (98, 'งานประกันสุขภาพ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (99, 'งานจัดเก็บรายได้');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (100, 'งานสังคมสงเคราะห์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (101, 'งานรักษาความปลอดภัย');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (102, 'ศูนย์รับผู้ป่วยนอน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (103, 'ศูนย์เครื่องมือแพทย์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (104, 'ห้องประชุมเพทาย');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (105, 'ห้องประชุมรัตมณี');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (106, 'ห้องประชุมบุษราคัม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (107, 'ห้องประชุมมรกต');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (108, 'ห้องประชุมพลอยชมพู');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (109, 'ห้องประชุมเพชรชมพู');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (110, 'ห้องประชุมพลอยไพลิน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (111, 'พรส.');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (112, 'เตาเผาขยะ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (113, 'ศูนย์จองห้องพิเศษ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (114, 'จัดซื้อจัดจ้าง');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (115, 'งานข้อมูลข่าวสาร');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (116, 'ห้องเภสัชสนเทศ (DIS)');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (117, 'กลุ่มงานเทคนิคการแพทย์(ล่าง)');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (118, 'กลุ่มงานเทคนิคการแพทย์(บน)');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (119, 'งานนิติเวช');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (120, 'ห้องเพาะเชื่อวัณโรค');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (121, 'ศูนย์เปล');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (122, 'งานเคมีบำบัด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (123, 'คลินิคประคับประคอง');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (124, 'งานบำบัดน้ำเสีย');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (125, 'ห้องสลายนิ่ว');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (126, 'ศูนย์ลูกค้าสัมพันธ์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (127, 'ICU ผู้ใหญ่');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (128, 'ICU เด็ก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (129, 'ICU Neuro');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (130, 'ศัลยกรรมหญิง');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (131, 'ทารกป่วย (Nursery)');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (132, 'สูติ-นรีเวชกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (133, 'งานอุบัติเหตุและฉุกเฉิน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (136, 'งานวิสัญญี');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (137, 'งาน IC');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (138, 'งานวิจัย');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (139, 'ห้องตา');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (140, 'งานส่องกล้อง');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (141, 'กลุ่มการพยาบาล');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (142, 'กุมารเวชกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (144, 'งานผู้ป่วยนอก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (145, 'งานเคลื่อนย้ายผู้ป่วย');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (146, 'จองห้องพิเศษ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (147, 'งานวางแผนครอบครัว /ฝากครรภ์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (148, 'กลุ่มงานยุทธศาสตร์และแผนงานโครงการ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (149, 'งานเวชระเบียนผู้ป่วยนอก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (150, 'งานเวชระเบียนผู้ป่วยใน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (151, 'ศูนย์ข้อมูลข่าวสาร');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (152, 'งานพัฒนาทรัพยากรบุคคล');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (153, 'งานพัฒนาคุณภาพ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (154, 'งานบริหารความเสี่ยง');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (155, 'กลุ่มงานการแพทย์แผนไทยและการแพทย์ทางเลือก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (156, 'งานระบาดวิทยาป้องกันและควบคุมโรค');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (157, 'งานสาธารณสุขชายแดน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (158, 'งานส่งเสริมสุขภาพและฟื้นฟู');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (159, 'กลุ่มงานสุขศึกษา');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (160, 'กลุ่มงานอาชีวเวชกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (161, 'กลุ่มงานการพยาบาลชุมชน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (162, 'คลินิกหมอครอบครัว');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (163, 'กลุ่มงานบริหารทั่วไป');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (164, 'กลุ่มงานพัสดุ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (165, 'กลุ่มงานโครงสร้างพื้นฐานและวิศวกรรมทางการแพทย์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (166, 'กลุ่มงานทรัพยากรบุคคล');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (167, 'กลุ่มงานการเงิน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (168, 'กลุ่มงานบัญชี');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (169, 'กลุ่มงานเวชศาสตร์ฉุกเฉิน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (170, 'กลุ่มงานอายุรกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (171, 'กลุ่มงานศัลยกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (172, 'กลุ่มงานศัลยกรรมออร์โธปิดิกส์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (173, 'กลุ่มงานกุมารเวชกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (174, 'กลุ่มงานนิติเวช');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (175, 'กลุ่มงานจักษุวิทยา');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (176, 'กลุ่มงานโสต ศอ นาสิก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (177, 'กลุ่มงานโภชนศาสตร์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (178, 'กลุ่มงานสูติ-นรีเวชกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (179, 'กลุ่มงานวิสัญญีวิทยา');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (180, 'กลุ่มงานจิตเวชและยาเสพติด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (181, 'กลุ่มงานรังสีวิทยา');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (182, 'กลุ่มงานเทคนิคการแพทย์และพยาธิวิทยาคลินิก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (183, 'รองผู้อำนวยการฝ่ายการแพทย์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (184, 'กลุ่มงานสังคมสงเคราะห์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (185, 'กลุ่มงานเภสัชกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (186, 'กลุ่มงานเวชกรรมฟื้นฟู');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (187, 'กลุ่มงานกายภาพบำบัด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (188, 'รองผู้อำนวยการด้านบริการปฐมภูมิ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (189, 'รองผู้อำนวยการฝ่ายบริหาร');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (190, 'รองผู้อำนวยการด้านพัฒนาระบบบริการและสนับสนุนบริการสุขภาพ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (191, 'รองผู้อำนวยการด้านการพยาบาล');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (192, 'หอผู้ป่วยพิเศษ SMC');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (193, 'คลินิค ONCO');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (194, 'ศูนย์ซ่อมคอมพิวเตอร์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (195, 'ประชุม/อบรม/กิจกรรม นอกสถานที่');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (197, 'คลินิกแม่สอดพัฒน์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (198, 'ห้องจ่ายยา คลินิกแม่สอดพัฒน์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (199, 'ห้องเจาะเลือด คลินิกแม่สอดพัฒน์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (200, 'ห้อง X-Ray คลินิกแม่สอดพัฒน์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (201, 'ห้องตรวจ VIP คลินิกแม่สอดพัฒน์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (202, 'คลินิคโรคหัวใจ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (203, 'งานศูนย์พึ่งได้ One Stop Crisis Center(OSCC)');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (204, 'หอผู้ป่วยพิเศษ 3 ชั้น 3');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (205, 'CT SCAN');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (206, 'ห้องให้เลือด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (210, 'หอผู้ป่วยพิเศษ 3 ชั้น 2');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (211, 'ศูนย์พัฒนาคุณภาพ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (213, 'COPD');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (214, 'ห้องทำแผล');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (215, 'ic');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (217, 'ศูนย์พักพิง');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (218, 'ศูนย์การเรียนรู้');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (219, 'ศูนย์การเรียนรู้ ชั้น 7');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (220, 'ห้องประชุมนิลนารา');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (221, 'แบคทีเรีย');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (222, '-');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (223, 'ไตเทียม2');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (224, 'งานเหล็ก');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (225, 'ห้องเจาะเลือด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (226, 'จุดนัดวิสัญญี');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (227, 'งานนิติกร');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (228, 'เวชศาสตร์ฟื้นฟู');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (229, 'Wellness Center');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (230, 'โครงการ Operation Smile');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (232, 'ICU Storke');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (233, 'ไม่ทราบ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (234, 'คัดกรองหน้าตึก GP');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (235, 'ร้านตากคอมพิวเตอร์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (236, 'กุมารเวชกรรม ชั้น 2');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (238, 'สุขภาพดิจิทัล');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (239, 'PLASTIC');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (240, 'คลินิกวัยรุ่น');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (241, 'ห้องประชุมทับทิมสยาม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (242, 'ห้องเก็บเงินเบอร์ 108');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (243, 'ห้องเก็บเงินเบอร์ 103');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (244, 'ห้องเก็บเงินเบอร์ 203');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (245, 'ห้องเก็บเงินต่างด้าวงานอาชีวเวชกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (246, 'เวชระเบียนผู้ป่วย ER');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (247, 'งานแผนไทย โรบินสัน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (248, 'ห้องจ่ายยานอกผู้ป่วยนอก 107');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (249, 'ห้องเก็บเงินคลินิกแม่สอดพัฒน์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (250, 'งานตรวจสุขภาพ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (251, 'กุมารเวชกรรม ชั้น 3');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (252, 'ศูนย์เทคโนโลยีสารสนเทศ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (253, 'ห้องจ่ายยา ศูนย์สุขภาพชุมชนแม่สอด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (254, 'ห้องฝังเข็ม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (255, 'ห้องจ่ายยานอกผู้ป่วยนอก 202');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (256, 'เวชระเบียนผู้ป่วยนอกหน้าห้องทันตกรรม');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (257, 'คลังผลิตยา');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (258, 'จุดพิมพ์คิวหน้าห้องประชาสัมพันธ์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (259, 'เวชระเบียน แม่สอดพัฒน์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (260, 'ศูนย์ทำความสะอาด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (261, 'LAB PATHO');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (262, 'มูลนิธิโรงพยาบาลแม่สอด');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (263, 'เวช');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (264, 'คลินิก SMC นอกเวลา');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (265, 'ห้องการเงินคลินิกแม่สอดพัฒน์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (266, 'Storke');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (267, 'เทคนิคการแพทย์ ตึกนิติเวช');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (268, 'FRIENDLY CLINIC');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (269, 'ห้องยา107');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (270, 'อยุรกรรมหญิง');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (271, 'ฟื้นฟู');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (272, 'ศูนย์รีเฟอร์');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (273, 'โครงการผ่าตัดตา');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (274, 'โครงการพิเศษ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (275, 'PCC');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (276, 'งานยุทธศาสตร์ ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (277, 'งานยุทธศาสตร์และแผนงานโครงการ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (278, 'ห้องประชุมแก้วโกเมน');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (279, 'ศูนย์ตรวจสอบสิทธิ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (280, 'CCP');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (281, 'CCU วิกฤตโรคหัวใจ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (282, 'คลินิกกฎหมาย');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (283, 'ศูนย์บริการสิทธิชำระเงินเองต่างชาติ');
INSERT INTO `depart` (`depart_id`, `depart_name`) VALUES (284, 'ECHO');
